### ISSUE TITLE
GeoOriginTransform

### ISSUE THREAD

**Issue by MBARIMike** [MBARIMike/papers#10]
I'm wondering if we should discuss the GeoOriginTransform node, perhaps in the context of it being an example of implementing an EXTERNPROTO type of capability. Perhaps in its own section before Applications...

**Comment by andreasplesch** [comment]
Time is getting short but we could give it a try. I had thought about a Future section which would touch on ideas such as this.

**Comment by MBARIMike** [comment]
Or it could be saved for a future paper... The current draft is nice and concise.

**Comment by MBARIMike** [comment]
Closed by https://github.com/MBARIMike/papers/pull/11
