### ISSUE TITLE
bib entries

### ISSUE THREAD

**Issue by andreasplesch** [MBARIMike/papers#15]
Enclose proper names in titles with braces to perserve capitalization

**Comment by MBARIMike** [comment]
See ftp://ftp.mbari.org/pub/mccann/X3DGeospatialComponent.pdf

**Comment by andreasplesch** [comment]
Looks good, thanks.

The long author line

author = {Plesch, A. and J. H. Shaw and C. Benson and W. A. Bryant and S. Carena and M. Cooke and J. Dolan and G. Fuis and E. Gath and L. Grant and E. Hauksson and T. Jordan and M. K\
amerling and M. Legg and S. Lindvall and H. Magistrale and C. Nicholson and N. Niemi and M. Oskin and S. Perry and G. Planansky and T. Rockwell and P. Shearer and C. Sorlien and M. P. S\
uess and J. Suppe and J. Treiman and R. Yeats},

has problems where it is broken into new lines with the back slashes.

If the back slashes are needed this might work better:

author = {Plesch, A. and J. H. Shaw and C. Benson and W. A. Bryant and S. Carena and M. Cooke and J. Dolan and G. Fuis and E. Gath and L. Grant and E. Hauksson and T. Jordan and\
M. Kamerling and M. Legg and S. Lindvall and H. Magistrale and C. Nicholson and N. Niemi and M. Oskin and S. Perry and G. Planansky and T. Rockwell and P. Shearer and C. Sorlien and\
M. P. Suess and J. Suppe and J. Treiman and R. Yeats},

**Comment by MBARIMike** [comment]
See ftp://ftp.mbari.org/pub/mccann/X3DGeospatialComponent.pdf
