### ISSUE TITLE
Shoemake 1985 reference is missing

### ISSUE THREAD

**Issue by MBARIMike** [MBARIMike/papers#17]
Needs to be added to the .bib file

**Comment by andreasplesch** [comment]
Non bibified:
Ken Shoemake, Animating Rotation with Quaternion Curves, Computer Graphics, Volume 19, Number 3, 1985.

**Comment by MBARIMike** [comment]
See ftp://ftp.mbari.org/pub/mccann/X3DGeospatialComponent.pdf
