### ISSUE TITLE
GeoOriginTransform subsection reword "This lets the non-geospatial..."

### ISSUE THREAD

**Issue by MBARIMike** [MBARIMike/papers#19]
Suggested wording: "This allows combining non-geospatial nodes together with geospatial nodes using the same GeoOrigin."

**Comment by andreasplesch** [comment]
Agreed.

On Tue, Mar 24, 2015 at 1:21 PM, Mike McCann notifications@github.com
wrote:

> Suggested wording: "This allows combining non-geospatial nodes together
> with geospatial nodes using the same GeoOrigin."
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MBARIMike/papers/issues/19.

## 

Andreas Plesch
39 Barbara Rd.
Waltham, MA 02453

**Comment by MBARIMike** [comment]
See ftp://ftp.mbari.org/pub/mccann/X3DGeospatialComponent.pdf
