### ISSUE TITLE
Enhance caption for Figure 1

### ISSUE THREAD

**Issue by MBARIMike** [MBARIMike/papers#20]
Change caption from this:

Screen capture of the STOQS web application showing underwater sensor data, models of instrumentation, and the terrain of Monterey Bay, California. X3D Geospatial nodes are used to enable effective interactive exploration of high resolution geospatial data.

to this:

Screen capture of the STOQS web application showing underwater sensor data, models of instrumentation, and the terrain of Monterey Bay, California. The X3D Geospatial component provides great flexibility for creating custom representations of geospatial data. This visualization applies 10x vertical exaggeration to enable effective interactive exploration of upper ocean biological data.

**Comment by andreasplesch** [comment]
Agree
