### ISSUE TITLE
Cozzi, 2014 reference for Cesium

### ISSUE THREAD

**Issue by andreasplesch** [MBARIMike/papers#8]
I believe P. Cozzi is the main author behind Cesium. We may want to reference him.

**Comment by MBARIMike** [comment]
Here's his answer from Twitter:

_Mike McCann_‏@MBARIMike https://twitter.com/MBARIMike

@CesiumJS https://twitter.com/CesiumJS What's the best reference to cite
for Cesium in an academic computer graphics journal publication?
0 replies0 retweets0 favorites
 Reply
 Retweet
 Favorite
View Tweet activity
More
4:35 PM - 9 Mar 2015
Tweet text
Reply to @CesiumJS https://twitter.com/CesiumJS
https://twitter.com/CesiumJS
1. _Patrick Cozzi_ ‏@pjcozzi  https://twitter.com/pjcozzi Mar 9
   https://twitter.com/pjcozzi/status/575159826822496256
   
   @MBARIMike https://twitter.com/MBARIMike @CesiumJS
   https://twitter.com/CesiumJS just http://cesiumjs.org
   http://t.co/gH05nUl1Ov should be good. Let us know when you can share
   your paper.
   https://twitter.com/pjcozzi/status/5751598268224962560 replies0
   retweets0 favorites
   Reply
   Retweet
   Favorite

**Comment by MBARIMike** [comment]
See https://github.com/MBARIMike/papers/commit/e08f703f22e9cc49c07391a1f4fbaa950a0e8a73
